[rules]
dynamic-function-decorator-return = "error"
missing-type-argument = "error"
possibly-unresolved-reference = "warn"
unsound-return-statement = "error"
blanket-ignore-comment = "error"
unsound-assignment = "error"
unsound-yield = "error"
unsupported-dynamic-base = "warn"
division-by-zero = "warn"
possibly-missing-attribute = "warn"
possibly-missing-import = "warn"

[analysis]
strict-literal-narrowing = true
strict-generic-narrowing = true
